# -*- coding: utf-8 -*-
"""TASK - 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AAQULXKFjMqsWE7JKif6jEd2uKrRVMxu
"""

!pip install yfinance transformers torch feedparser pandas numpy matplotlib

import yfinance as yf
import pandas as pd
import numpy as np
import feedparser
import datetime
from transformers import pipeline

sentiment_model = pipeline(
    "sentiment-analysis",
    model="ProsusAI/finbert"
)

# PROSUS AI - MODEL PUBLISHER
# FINBERT - MODEL NAME

COMPANY_TICKERS = {
    "apple": "AAPL",
    "microsoft": "MSFT",
    "google": "GOOGL",
    "amazon": "AMZN",
    "tesla": "TSLA",
    "tejasnet" : "TEJASNET"
}

def extract_ticker(question):
    question = question.lower()
    for company, ticker in COMPANY_TICKERS.items():
        if company in question:
            return ticker
    return None

def get_stock_data(ticker, period="3mo"):
    stock = yf.Ticker(ticker)
    df = stock.history(period=period)
    return df

def analyze_trend(df):
    df["Return"] = df["Close"].pct_change()

    recent_return = df["Return"].tail(5).mean()

    if recent_return > 0.01:
        return "up"
    elif recent_return < -0.01:
        return "down"
    else:
        return "stable"

def fetch_news(company):
    url = f"https://news.google.com/rss/search?q={company}+stock"
    feed = feedparser.parse(url)
    articles = []

    for entry in feed.entries[:5]:
        articles.append(entry.title)

    return articles

def analyze_news_sentiment(news_list):
    sentiments = sentiment_model(news_list)

    score = 0
    for s in sentiments:
        if s["label"] == "positive":
            score += 1
        elif s["label"] == "negative":
            score -= 1

    return score

def stock_chatbot(question):
    ticker = extract_ticker(question)

    if ticker is None:
        return "Sorry, I couldn't identify the company."

    company = [k for k, v in COMPANY_TICKERS.items() if v == ticker][0].capitalize()

    df = get_stock_data(ticker)
    trend = analyze_trend(df)

    news = fetch_news(company)
    sentiment_score = analyze_news_sentiment(news)

    response = f"Analysis for {company} ({ticker}):\n\n"

    if trend == "down":
        response += "The stock has declined recently.\n"
    elif trend == "up":
        response += "The stock has shown an upward trend recently.\n"
    else:
        response += "The stock has been relatively stable.\n"

    if sentiment_score < 0:
        response += "Recent news sentiment is mostly negative, which may explain the movement.\n"
    elif sentiment_score > 0:
        response += "Recent news sentiment is mostly positive, supporting the price movement.\n"
    else:
        response += "News sentiment appears mixed.\n"

    response += "\n Key News Headlines:\n"

    for n in news:
        response += f"- {n}\n"
    return response

import matplotlib.pyplot as plt

def chatbot_with_stock_plot(question):
    response = stock_chatbot(question)
    print(response)

    ticker = extract_ticker(question)
    if ticker is None:
        print("No ticker found for plotting.")
        return

    df = get_stock_data(ticker, period="6mo")

    plt.figure(figsize=(12, 6))
    plt.plot(df.index, df["Close"])
    plt.title(f"{ticker} Stock Price (Last 6 Months)")
    plt.xlabel("Date")
    plt.ylabel("Closing Price")
    plt.show()

question = "Why did Tesla's stock drop "
chatbot_with_stock_plot(question)
