# -*- coding: utf-8 -*-
"""TASK - 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rv5YW_a--d56PQFJEOzmgjlYpF0T9Uk0
"""

!pip install yfinance plotly pandas

import yfinance as yf
import pandas as pd
import time
from datetime import datetime
import plotly.graph_objects as go
from IPython.display import display, clear_output

SYMBOL = "BTC-USD"
UPPER_THRESHOLD = 105000
LOWER_THRESHOLD = 95000

BACKFILL_PERIOD = "7d"
LIVE_UPDATE_INTERVAL = 30

print("Downloading 1 week historical data...")
df = yf.download(SYMBOL, period=BACKFILL_PERIOD, interval="5m", progress=False)
df = df.reset_index()[["Datetime", "Close"]]
df.columns = ["time", "price"]

print("Backfill completed:", len(df), "records")

try:
    while True:
        live = yf.download(SYMBOL, period="1d", interval="1m", progress=False)
        latest_time = live.index[-1]
        latest_price = live[('Close', SYMBOL)].iloc[-1]
        new_row = pd.DataFrame([[latest_time, latest_price]], columns=["time", "price"])
        df = pd.concat([df, new_row]).tail(2000)

        alert = ""
        if latest_price >= UPPER_THRESHOLD:
            alert = f"ALERT: Price crossed upper target {UPPER_THRESHOLD}"
        elif latest_price <= LOWER_THRESHOLD:
            alert = f"ALERT: Price dropped below support {LOWER_THRESHOLD}"

        clear_output(wait=True)
        fig = go.Figure()

        fig.add_trace(go.Scatter(
            x=df["time"],
            y=df["price"],
            mode="lines",
            name="BTC Price"
        ))

        fig.add_hline(y=UPPER_THRESHOLD, line_dash="dash", line_color="green")
        fig.add_hline(y=LOWER_THRESHOLD, line_dash="dash", line_color="red")

        fig.update_layout(
            title="BTC Price – 1 Week History + Live Updates (Every 10 min)",
            xaxis_title="Time",
            yaxis_title="Price (USD)",
            template="plotly_dark",
            height=600
        )

        display(fig)
        print("Last update:", latest_time)
        print("Current price: $", round(latest_price, 2))
        if alert:
            print(alert)

        print("\nNext live update in 30 seconds...")
        time.sleep(LIVE_UPDATE_INTERVAL)

except KeyboardInterrupt:
    print("System stopped.")

import yfinance as yf
SYMBOL = "BTC-USD"
live = yf.download(SYMBOL, period="1d", interval="1m", progress=False)
live.head()
