"""TASK - 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gGFq6E4zu6ViE1ZS4vveGs6ik1aR0UWU
"""

!pip install yfinance

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error

import yfinance as yf
df = yf.download("AAPL", start="2019-01-01", end="2026-01-01")

close_prices = df[['Close']].values

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(close_prices)

from sklearn.preprocessing import MinMaxScaler

close_prices = df[['Close']].values
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(close_prices)

def create_sequences(data, window: int, horizon: int):
    X, y = [], []
    for i in range(len(data) - window - horizon):
        X.append(data[i:i+window])
        y.append(data[i+window:i+window+horizon])
    return np.array(X), np.array(y)

window = 7
horizon = 100

X, y = create_sequences(scaled_data, window, horizon)

split = int(0.8 * len(X))

X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

X.shape

model = Sequential([
    LSTM(64, return_sequences=True, input_shape=(window, 1)),
    Dropout(0.3),
    LSTM(32),
    Dropout(0.3),
    Dense(horizon)
])

model.compile(
    optimizer='adam',
    loss='mse'
)

model.summary()

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

history = model.fit(
    X_train, y_train,
    validation_split=0.1,
    epochs=50,
    batch_size=32,
    #callbacks=[early_stop]
)

y_pred_scaled = model.predict(X_test)

y_pred_real = []

for i in range(y_pred_scaled.shape[0]):
    pred_7days = y_pred_scaled[i].reshape(-1,1)
    pred_7days_real = scaler.inverse_transform(pred_7days)
    y_pred_real.append(pred_7days_real)

y_pred_real = np.array(y_pred_real)
y_pred_real.shape

def mc_dropout_prediction(model, input_window, n_simulations=100):
    predictions = []
    for i in range(n_simulations):
        pred = model(input_window, training=True)
        predictions.append(pred.numpy())
    predictions = np.array(predictions)
    return predictions

last_window = scaled_data[-window:]

last_window = last_window.reshape(1, window, 1)

mc_predictions = mc_dropout_prediction(model, last_window, n_simulations=100)

mean_forecast_scaled = mc_predictions.mean(axis=0)

lower_bound_scaled = np.percentile(mc_predictions, 10, axis=0)
upper_bound_scaled = np.percentile(mc_predictions, 90, axis=0)

mean_forecast = scaler.inverse_transform(mean_forecast_scaled.reshape(-1,1)).flatten()
lower_bound = scaler.inverse_transform(lower_bound_scaled.reshape(-1,1)).flatten()
upper_bound = scaler.inverse_transform(upper_bound_scaled.reshape(-1,1)).flatten()

plt.figure(figsize=(12,6))

plt.plot(df.index[-100:], df['Close'].values[-100:], label="Historical")

future_dates = pd.date_range(df.index[-1], periods=horizon+1, freq='B')[1:]

plt.plot(future_dates, mean_forecast, label="Forecast", color='red')
plt.fill_between(
    future_dates,
    lower_bound,
    upper_bound,
    color='red',
    alpha=0.3,
    label="Confidence Interval"
)

plt.title("7-Day Stock Price Forecast with Uncertainty")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.show()
