# -*- coding: utf-8 -*-
"""TASK - 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gGFq6E4zu6ViE1ZS4vveGs6ik1aR0UWU
"""

!pip install yfinance

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error

import yfinance as yf
df = yf.download("AAPL", start="2019-01-01", end="2026-01-01")

close_prices = df[['Close']].values

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(close_prices)

from sklearn.preprocessing import MinMaxScaler

close_prices = df[['Close']].values
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(close_prices)

def create_sequences(data, window: int, horizon: int):
    X, y = [], []
    for i in range(len(data) - window - horizon):
        X.append(data[i:i+window])
        y.append(data[i+window:i+window+horizon])
    return np.array(X), np.array(y)

window = 7
horizon = 100

X, y = create_sequences(scaled_data, window, horizon)

split = int(0.8 * len(X))

X_train_full, X_test_full = X[:split], X[split:]
y_train_full, y_test_full = y[:split], y[split:]

X.shape

def build_model():
    model = Sequential([
        LSTM(64, return_sequences=True, input_shape=(window, 1)),
        Dropout(0.3),
        LSTM(32),
        Dropout(0.3),
        Dense(horizon)
    ])
    model.compile(optimizer="adam", loss="mse")
    return model

model = build_model()
model.summary()

early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

history = model.fit(
    X_train_full, y_train_full,
    validation_split=0.1,
    epochs=50,
    batch_size=32,
    #callbacks=[early_stop]
)

y_pred_scaled = model.predict(X_test_full)

y_test_real = []
y_pred_real = []

for i in range(y_pred_scaled.shape[0]):
    y_test_real.append(scaler.inverse_transform(y_test_full[i].reshape(-1,1)))
    y_pred_real.append(scaler.inverse_transform(y_pred_scaled[i].reshape(-1,1)))

y_test_real = np.array(y_test_real)
y_pred_real = np.array(y_pred_real)

mae = mean_absolute_error(
    y_test_real.flatten(),
    y_pred_real.flatten()
)

rmse = np.sqrt(mean_squared_error(
    y_test_real.flatten(),
    y_pred_real.flatten()
))

print("MODEL PERFORMANCE")
print("MAE :", mae)
print("RMSE:", rmse)

print("ROLLING FORECAST VALIDATION")

rolling_mae = []
rolling_rmse = []

step = 50

for i in range(0, len(X_test_full), step):
    X_roll = X_test_full[i:i+step]
    y_roll = y_test_full[i:i+step]

    if len(X_roll) == 0:
        break

    y_roll_pred = model.predict(X_roll)

    y_roll_real = []
    y_roll_pred_real = []

    for j in range(len(y_roll_pred)):
        y_roll_real.append(scaler.inverse_transform(y_roll[j].reshape(-1,1)))
        y_roll_pred_real.append(scaler.inverse_transform(y_roll_pred[j].reshape(-1,1)))

    y_roll_real = np.array(y_roll_real)
    y_roll_pred_real = np.array(y_roll_pred_real)

    roll_mae = mean_absolute_error(
        y_roll_real.flatten(),
        y_roll_pred_real.flatten()
    )

    roll_rmse = np.sqrt(mean_squared_error(
        y_roll_real.flatten(),
        y_roll_pred_real.flatten()
    ))

    rolling_mae.append(roll_mae)
    rolling_rmse.append(roll_rmse)

    print(f"Window {i} → MAE: {roll_mae:.2f}, RMSE: {roll_rmse:.2f}")

print("\nAverage Rolling MAE :", np.mean(rolling_mae))
print("Average Rolling RMSE:", np.mean(rolling_rmse))

def mc_dropout_prediction(model, input_window, n_simulations=100):
    predictions = []
    for i in range(n_simulations):
        pred = model(input_window, training=True)
        predictions.append(pred.numpy())
    return np.array(predictions)

last_window = scaled_data[-window:].reshape(1, window, 1)

mc_predictions = mc_dropout_prediction(model, last_window, 100)

mean_forecast_scaled = mc_predictions.mean(axis=0)
lower_bound_scaled = np.percentile(mc_predictions, 10, axis=0)
upper_bound_scaled = np.percentile(mc_predictions, 90, axis=0)

mean_forecast = scaler.inverse_transform(mean_forecast_scaled.reshape(-1,1)).flatten()
lower_bound = scaler.inverse_transform(lower_bound_scaled.reshape(-1,1)).flatten()
upper_bound = scaler.inverse_transform(upper_bound_scaled.reshape(-1,1)).flatten()

plt.figure(figsize=(12,6))
plt.plot(df.index[-100:], df['Close'].values[-100:], label="Historical")
future_dates = pd.date_range(df.index[-1], periods=horizon+1, freq='B')[1:]
plt.plot(future_dates, mean_forecast, label="Forecast", color='red')
plt.fill_between(future_dates, lower_bound, upper_bound, alpha=0.3, color='red', label="Uncertainty")
plt.title("Rolling Forecast with Uncertainty")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.show()
